# Site settings
title: Irka's portfolio
email: #ibushmeleva@gmail.com
description: Works unsurpassed designer of our time # this means to ignore newlines until "baseurl:"
baseurl: "portfolio" # the subpath of your site, e.g. /blog/
url: "http://ibushmeleva.github.io/portfolio" #"http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ibushmeleva
github_username:  ibushmeleva
facebook_username: iren.bushmeleva
# Build settings
markdown: kramdown
permalink: pretty
